import os

def build_markdown_report(records):
    """
    Terima list of dict:
      {nim, nama, hadir, nilai_akhir, predikat}
    Kembalikan string Markdown berisi tabel rekap.
    """
    lines = []
    lines.append("# Rekap Nilai Mahasiswa")
    lines.append("")
    lines.append("| NIM | Nama | Hadir (%) | Nilai Akhir | Predikat |")
    lines.append("|----|------|-----------:|------------:|:--------:|")
    for r in records:
        lines.append(
            f"| {r['nim']} | {r['nama']} | {r['hadir']:.1f} | {r['nilai_akhir']:.2f} | {r['predikat']} |"
        )
    lines.append("")
    lines.append("Generated by student_performance_tracker")
    return "\n".join(lines)

def save_text(path, content):
    """
    Simpan content teks ke path (buat folder jika belum ada).
    """
    folder = os.path.dirname(path)
    if folder and not os.path.exists(folder):
        os.makedirs(folder, exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        f.write(content)
    return path