import os
from html import escape

def build_markdown_report(records):
    lines = []
    lines.append("# Rekap Nilai Mahasiswa")
    lines.append("")
    lines.append("| NIM | Nama | Hadir (%) | Nilai Akhir | Predikat |")
    lines.append("|----|------|-----------:|------------:|:--------:|")
    for r in records:
        lines.append(
            f"| {r['nim']} | {r['nama']} | {r['hadir']:.1f} | {r['nilai_akhir']:.2f} | {r['predikat']} |"
        )
    lines.append("")
    lines.append("Generated by student_performance_tracker")
    return "\n".join(lines)

def build_html_report(records):
    """
    Buat tabel HTML sederhana. Predikat diberi warna:
      A hijau, B biru, C oranye, D merah, E merah tua.
    """
    color = {
        "A": "#16a34a",
        "B": "#2563eb",
        "C": "#f59e0b",
        "D": "#ef4444",
        "E": "#991b1b",
    }
    rows = []
    for r in records:
        pred = r["predikat"]
        c = color.get(pred, "#111827")
        rows.append(
            f"<tr>"
            f"<td>{escape(str(r['nim']))}</td>"
            f"<td>{escape(str(r['nama']))}</td>"
            f"<td style='text-align:right'>{r['hadir']:.1f}</td>"
            f"<td style='text-align:right'>{r['nilai_akhir']:.2f}</td>"
            f"<td style='color:{c}; text-align:center; font-weight:600'>{pred}</td>"
            f"</tr>"
        )
    html = f"""<!doctype html>
<html>
<head>
<meta charset="utf-8">
<title>Rekap Nilai Mahasiswa</title>
<style>
body {{ font-family: system-ui, -apple-system, Segoe UI, Roboto, sans-serif; padding: 24px; }}
table {{ border-collapse: collapse; width: 100%; max-width: 800px; }}
th, td {{ border: 1px solid #e5e7eb; padding: 8px 10px; }}
th {{ background: #f3f4f6; text-align: left; }}
tfoot td {{ font-size: 12px; color: #6b7280; border: none; padding-top: 12px; }}
</style>
</head>
<body>
<h1>Rekap Nilai Mahasiswa</h1>
<table>
<thead>
<tr>
<th>NIM</th><th>Nama</th><th>Hadir (%)</th><th>Nilai Akhir</th><th>Predikat</th>
</tr>
</thead>
<tbody>
{''.join(rows)}
</tbody>
</table>
<tfoot><tr><td colspan="5">Generated by student_performance_tracker</td></tr></tfoot>
</body>
</html>"""
    return html

def save_text(path, content):
    folder = os.path.dirname(path)
    if folder and not os.path.exists(folder):
        os.makedirs(folder, exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        f.write(content)
    return path